# Generated by Django 4.0.6 on 2022-08-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_contacted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
