# Generated by Django 4.0.6 on 2022-07-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_team_delete_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='google_plus_link',
            new_name='instagram_link',
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin_link',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
