# Generated by Django 4.0.6 on 2022-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_social_alter_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='copyright_year',
            field=models.IntegerField(default=2022, max_length=4),
        ),
    ]
