# Generated by Django 4.0.6 on 2022-07-30 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_social_copyright_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='copyright_year',
            field=models.DecimalField(decimal_places=0, default=2022, max_digits=4, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
