# Generated by Django 4.0.6 on 2022-07-31 04:22

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_social_copyright_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('startday', models.CharField(max_length=20)),
                ('endday', models.CharField(max_length=20)),
                ('opentime', models.CharField(max_length=10)),
                ('closetime', models.CharField(max_length=10)),
                ('copyright_year', models.DecimalField(decimal_places=0, default=2022, max_digits=4, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2022)])),
                ('facebook', models.URLField(blank=True, unique=True)),
                ('twitter', models.URLField(blank=True, unique=True)),
                ('instagram', models.URLField(blank=True, unique=True)),
                ('linkedIn', models.URLField(blank=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
