# Generated by Django 4.0.6 on 2022-07-31 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_companydetail_delete_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='copyright_year',
        ),
    ]
