# Generated by Django 4.0.6 on 2022-07-31 05:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_companydetail_fax_companydetail_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='web',
            field=models.URLField(unique=True),
        ),
    ]
