# Generated by Django 4.0.6 on 2022-08-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_companydetail_fax_alter_companydetail_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='rss',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
